services:
  ovh_sms:
    class: Geolim4\OvhSmsBundle\Service\OvhSms
    arguments: [ %geolim4_ovh_sms.sender%, %geolim4_ovh_sms.application_key%, %geolim4_ovh_sms.application_secret%, %geolim4_ovh_sms.consumer_key%, %geolim4_ovh_sms.sms_service_id%, %geolim4_ovh_sms.endpoint%]
